export const TOURNAMENTS_REPOSITORY_TOKEN = 'TOURNAMENTS_REPOSITORY_TOKEN';
export const TOURNAMENTS_MEMBERS_REPOSITORY_TOKEN =
  'TOURNAMENTS_MEMBERS_REPOSITORY_TOKEN';
export const TOURNAMENT_RELATIONS_CONNECTION =
  'TOURNAMENT_RELATIONS_CONNECTION';
